liip_imagine:
    loaders:
        avata:
            flysystem:
                filesystem_service: oneup_flysystem.avata_filesystem
    data_loader: avata

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        avata_thumb_120x120:
            quality: 75
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 120], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                #background: { size: [124, 94], position: center, color: '#000000' }

        avata_thumb_25x25:
            quality: 75
            filters:
                thumbnail: { size: [25, 25], mode: outbound }
