sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                avata: 'sonata/admin/user/list/avata.html.twig'
            show:
                avata: 'sonata/admin/user/show/avata.html.twig'
                fullname: 'sonata/admin/user/show/fullname.html.twig'
